name: Release CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Config
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Compile
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/themer
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
